In [1]:
import numpy as np

# NumPy的ndarray:一种多维数组对象

In [2]:
data = np.random.randn(10)
data

array([-0.83734584, -0.84880968,  0.5670995 ,  0.06814374, -0.05668469,
        0.06325027, -0.01855171, -0.85260012, -0.01695794, -0.39094573])

In [3]:
data * 10

array([-8.37345841, -8.48809678,  5.67099504,  0.68143736, -0.56684692,
        0.6325027 , -0.18551712, -8.5260012 , -0.16957937, -3.90945733])

In [4]:
data + data

array([-1.67469168, -1.69761936,  1.13419901,  0.13628747, -0.11336938,
        0.12650054, -0.03710342, -1.70520024, -0.03391587, -0.78189147])

In [5]:
# ndarray中的数据必须是相同类型
print data.shape    #数组各维度大小
print data.dtype    #数组数据类型

(10,)
float64


In [6]:
# 创建ndarray
# 1.使用array函数,接收一切序列型对象
data1 = list('abcdefg')
arr1 = np.array(data1)
arr1

array(['a', 'b', 'c', 'd', 'e', 'f', 'g'], 
      dtype='|S1')

In [7]:
# 嵌套序列会被装换成多维数组
data2 = [[1,2,3],[4,5,6]]
arr2 = np.array(data2)
print arr2.ndim    #ndim维度 
print arr2.shape

2
(2, 3)


In [9]:
# 可以新建ndarray的一些函数
np.zeros((2, 3, 4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [13]:
# 没有任何具体值的数组
np.empty((4,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [14]:
# 数组版range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# asarray将输入转换为ndarray
np.asarray(data1)

array(['a', 'b', 'c', 'd', 'e', 'f', 'g'], 
      dtype='|S1')

In [20]:
# 根据指定指定的形状和dtype创造一个全1的数组
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
# 以另一个数组作为参数,以其形状构建一个全1数组
np.ones_like(arr2)

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
# zeros,zeros_like
print np.zeros((3,4))
print np.zeros_like(arr2)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[0 0 0]
 [0 0 0]]


In [26]:
# empty,empyt_like,创建新数组,只分配内存空间,不分填充值
print np.empty((3,4))
print np.empty_like(arr2)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[0 0 0]
 [0 0 0]]


In [29]:
# 创建一个正方的N*N单位矩阵,对角线为1,其余为0
print np.eye(4)
print np.identity(4)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [33]:
# ndarray的数据类型 dtype
#dtype含有将一块内存解释为特定数据类型所需的信息
arr3 = np.array(data2,dtype=np.float64)
print arr3
print arr3.dtype

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
float64


In [42]:
# 显示的转换dtype
arr4 = arr3.astype(np.int64)
arr5 = arr4.astype(arr2.dtype)

print arr4,'\n'
print arr5

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]]
